feat: Endevor Bridge for Git integration
BroadcomMFD-DevOps/che-che4z-lsp-for-hlasm pull request #89
Opened 2022-09-07 15:47 UTC by slavek-kucera

2022-09-08 10:58 UTC, zeibura requested changes

2022-09-08 10:58 UTC, zeibura commented on clients/vscode-hlasmplugin/schema/proc_grps.schema.json
> +                                            "description": "Indicates that relative paths should be evaluated with respect to an alternative root folder (e.g. provided by the Endevor Bridge for Git).
Specify "true" to resolve relative paths with respect to a different root folder than the workspace root (e.g. a folder provided by Endevor Bridge for Git)

2022-09-08 10:58 UTC, zeibura commented on clients/vscode-hlasmplugin/README.md
> +The `pgm_conf.json` file may be provided implicitly by another product that supports integration with the HLASM Language support (e.g. Endevor Bridge for Git integration).
The `pgm_conf.json` file can be provided implicitly by another product that supports integration with HLASM Language Support (e.g. Endevor Bridge for Git).

2022-09-12 12:16 UTC, slavek-kucera commented on parser_library/src/workspaces/workspace.cpp
> +#include "file_manager.h"
file_manager_vfm is needed

2022-09-12 12:18 UTC, jirimosinger commented on parser_library/src/workspaces/workspace.cpp
> +#include "file_manager.h"
I've meant also the rest of the includes but github didn't allow me to select the lines which were not edited...

2022-09-12 12:18 UTC, slavek-kucera commented on parser_library/src/workspaces/workspace_configuration.cpp
> +        return false;
the function simply says if something *changed*.

2022-09-12 12:23 UTC, jirimosinger commented on parser_library/src/workspaces/workspace_configuration.cpp
> +        return false;
Alright

2022-09-12 14:04 UTC, slavek-kucera commented on parser_library/src/workspaces/workspace.cpp
> +#include "file_manager.h"
been looking into `workspace.h`... I'll recheck.

2022-09-12 15:21 UTC, merged